import { useRef, useState } from 'react';
import { Download, Upload, ShieldCheck, RotateCcw, HardDrive, Smartphone, FileCheck2, AlertTriangle } from 'lucide-react';
import { useShop } from '../state/ShopContext';
import { parseBackup } from '../domain/backup';
import type { ShopState } from '../domain/types';
import { Modal, Tag } from '../components/ui';
import { timeLabel } from '../lib/format';

export function Backup(){
  const {shop,demo,busy,exportBackup,importBackup,rollback,notify}=useShop();const [preview,setPreview]=useState<{state:ShopState;exportedAt:string;filename:string}|null>(null);const [accepted,setAccepted]=useState(false);const [reading,setReading]=useState(false);const [undo,setUndo]=useState(false);const [storage,setStorage]=useState('');const input=useRef<HTMLInputElement>(null);
  const state=shop!.state;const dirty=state.revision>shop!.backup.confirmedRevision;
  async function readFile(file?:File){if(!file)return;setReading(true);setAccepted(false);try{if(file.size>20*1024*1024)throw new Error('文件超过20MB，请选择小店记导出的 JSON 备份。');const parsed=await parseBackup(await file.text());setPreview({...parsed,filename:file.name});}catch(e){notify(`备份未导入：${e instanceof Error?e.message:'文件格式不正确'}`,true);}finally{setReading(false);if(input.current)input.current.value='';}}
  async function restore(){if(!preview||!accepted)return;try{await importBackup(preview.state);setPreview(null);}catch{/* context reports failure; preview remains */}}
  async function protect(){try{const ok=await navigator.storage?.persist?.();setStorage(ok?'浏览器已允许持久存储，仍请定期导出备份。':'浏览器未授予持久存储，请继续定期导出备份。');}catch{setStorage('当前浏览器不支持此功能，导出备份仍然可用。');}}
  return <><div className="page-title"><div><h1>备份与恢复</h1><p>记录留在手机里，备份文件请另外存好。</p></div><Tag tone="green"><HardDrive size={14}/>本机保存</Tag></div>
    <section className="backup-hero"><span className="backup-art"><ShieldCheck size={44} strokeWidth={1.3}/></span><div><h2>{dirty?'有新的记录，记得备份':'给小店的记录多留一份'}</h2><p>保存到本机不等于已备份。导出文件后，最好再存到其他设备。</p><div className="backup-facts"><span>本机版本：第 {state.revision} 版</span><span>上次确认备份：{timeLabel(shop!.backup.confirmedAt)}</span></div></div><button className="btn primary" disabled={demo||busy} onClick={()=>void exportBackup()}><Download size={18}/>导出最新备份</button></section>
    <div className="backup-grid"><section className="panel guide-card"><div className="section-head"><h2><Upload size={20}/>从文件恢复</h2></div><p>换手机、换浏览器，或找回之前的数据时，选择您导出的备份文件。</p><p className="small muted">会先检查文件并显示预览，确认之前不会改变当前记录。</p><input ref={input} type="file" accept=".json,application/json" hidden onChange={e=>void readFile(e.target.files?.[0])}/><button className="btn" disabled={demo||busy||reading} onClick={()=>input.current?.click()}><Upload size={17}/>{reading?'正在检查文件…':'选择备份文件'}</button></section>
    <section className="panel guide-card"><div className="section-head"><h2><RotateCcw size={20}/>找回恢复前的数据</h2></div><p>{shop!.recovery?`已保留上一次恢复前的本机数据，共${shop!.recovery.products.length}种商品。`:'每次从文件恢复时，系统会先在本机留一份原来的数据。'}</p><p className="small muted">只保留最近一次恢复前的数据，仍需自行保存导出的备份。</p><button className="btn" disabled={demo||busy||!shop!.recovery} onClick={()=>setUndo(true)}>查看并找回</button></section></div>
    <section className="panel guide-card"><h2>妗妗只要记住这三步</h2><ol className="guide-steps"><li><Smartphone size={22}/><div><strong>改完资料，点“确认保存”</strong><p>看到“已保存到本机”才算记好了。没有保存成功时，请保留填写内容。</p></div></li><li><Download size={22}/><div><strong>看到提醒，点“导出最新备份”</strong><p>在手机的下载文件或文件管理里，找到“小店记备份… .json”，再点“我已保存好文件”。</p></div></li><li><FileCheck2 size={22}/><div><strong>每天收店，另存一份</strong><p>建议把最新文件存到另一台手机、电脑或自己的文件空间。手机丢失时，手机里的文件也会一起丢失。</p></div></li></ol><div className="notice amber"><AlertTriangle size={20}/><span>请固定使用同一个网址和浏览器。不要用无痕模式，也不要清理该网站的数据。浏览器被清理后，需要用导出的文件恢复。</span></div><button className="link-btn" onClick={()=>void protect()}>申请浏览器保留本机数据</button>{storage&&<p className="small muted" role="status">{storage}</p>}</section>
    {preview&&<Modal title="检查备份，再确认恢复" onClose={()=>!busy&&setPreview(null)}><div className="modal-body"><Tag tone="green">文件格式与校验通过</Tag><p className="small file-name">{preview.filename}</p><dl className="review-list"><div><dt>备份时间</dt><dd>{timeLabel(preview.exportedAt)}</dd></div><div><dt>小店名称</dt><dd>{preview.state.settings.shopName}</dd></div><div><dt>商品 / 供应商</dt><dd>{preview.state.products.length} 种 / {preview.state.suppliers.length} 家</dd></div><div><dt>批次 / 进货记录</dt><dd>{preview.state.batches.length} 批 / {preview.state.purchases.length} 条</dd></div></dl><div className="notice amber">恢复会替换当前 {state.products.length} 种商品及其他记录，不是合并。当前数据会在本机保留一份供找回。</div><button className="btn gap-top" onClick={()=>void exportBackup()}>先导出当前数据</button><label className="check-line"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>我已核对备份日期和内容，确认替换当前记录</label></div><div className="modal-foot"><button className="btn" disabled={busy} onClick={()=>setPreview(null)}>取消</button><button className="btn danger" disabled={!accepted||busy} onClick={()=>void restore()}>{busy?'正在恢复…':'确认恢复这份备份'}</button></div></Modal>}
    {undo&&<Modal title="找回上次恢复前的数据" onClose={()=>!busy&&setUndo(false)}><div className="modal-body"><p>将恢复为上次导入前的 {shop!.recovery?.products.length} 种商品、{shop!.recovery?.purchases.length} 条进货记录，替换当前数据。</p><p className="notice amber">请先导出当前数据。恢复后请再次检查数量和日期。</p></div><div className="modal-foot"><button className="btn" disabled={busy} onClick={()=>setUndo(false)}>取消</button><button className="btn danger" disabled={busy} onClick={async()=>{try{await rollback();setUndo(false);}catch{/* error shown */}}}>确认找回</button></div></Modal>}
  </>;
}
