import { useState } from 'react';
import { Plus, Search, ChevronRight, Pencil, ClipboardCheck } from 'lucide-react';
import { useShop } from '../state/ShopContext';
import { Empty, Glyph, Modal, Tag } from '../components/ui';
import { stockOf, latestQuotes } from '../domain/selectors';
import { dateLabel, money, unitPrice } from '../lib/format';
import type { Editor } from './Editors';

export function Products({ edit }: { edit: (editor: Editor) => void }) {
  const { shop } = useShop(); const state = shop!.state; const [search, setSearch] = useState(''); const [category, setCategory] = useState('全部'); const [selected, setSelected] = useState('');
  const products = state.products.filter(p => (category === '停用' ? !p.active : p.active && (category === '全部' || p.category === category)) && `${p.name}${p.spec}`.toLowerCase().includes(search.toLowerCase()));
  const product = state.products.find(p => p.id === selected); const quotes = product ? latestQuotes(state,product.id) : [];
  const batchList = product ? state.batches.filter(b => b.productId === product.id).sort((a,b) => Number(b.remaining > 0) - Number(a.remaining > 0) || (a.expiryDate ?? '9999').localeCompare(b.expiryDate ?? '9999')) : [];
  return <><div className="page-title"><div><h1>商品与库存</h1><p>少记一点，记准一点。按批次核对货架上的数量。</p></div><button className="btn primary" onClick={() => edit({type:'product'})}><Plus size={18}/>添加商品</button></div>
    <div className="toolbar"><label className="search"><Search size={19}/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="搜索商品名称、规格" aria-label="搜索商品"/></label><button className="btn" onClick={() => edit({type:'batch'})}><ClipboardCheck size={17}/>登记现有库存</button></div>
    <div className="tabs">{['全部','饮料','食品','日用品','烟酒','其他','停用'].map(c => <button key={c} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div>
    <section className="panel">{products.length ? <><div className="table-header product-table"><span>商品 / 规格</span><span>记录库存</span><span>补货目标</span><span>近期参考单价</span><span/></div>{products.map(p => {const stock = stockOf(state,p.id); const quote = latestQuotes(state,p.id)[0]; return <button className="product-table product-row" key={p.id} onClick={() => setSelected(p.id)}><span className="product-name"><Glyph category={p.category}/><span><strong>{p.name}</strong><small>{p.spec} · 1箱={p.packSize}{p.unit}</small></span></span><span className="stock-cell"><strong className={stock <= p.minStock ? 'warning-text' : ''}>{stock}<small>{p.unit}</small></strong>{stock <= p.minStock && <Tag tone="amber">需补货</Tag>}</span><span className="desktop-cell muted">{p.targetStock}{p.unit}</span><span className="desktop-cell">{quote ? unitPrice(quote.priceCents,quote.packSize) : '暂无报价'}<small className="block muted">{quote ? `每${p.unit} · ${dateLabel(quote.date)}` : '添加后可比价'}</small></span><ChevronRight size={18} className="muted"/></button>;})}</> : <Empty title={search ? '没有找到这个商品' : '这里还没有商品'} description="可以先添加最常进货的饮料、食品，再慢慢补齐。"/>}</section>
    {product && <Modal title={product.name} onClose={() => setSelected('')} wide><div className="modal-body"><div className="detail-heading"><Glyph category={product.category}/><div><p>{product.spec} · {product.category}</p><strong>记录库存 {stockOf(state,product.id)} {product.unit}</strong></div><button className="btn small-btn" onClick={() => {setSelected('');edit({type:'product',product});}}><Pencil size={16}/>资料</button></div>
      <div className="detail-actions"><button className="btn primary" disabled={!product.active} onClick={() => {setSelected('');edit({type:'receive',productId:product.id});}}>记录到货</button><button className="btn" disabled={!product.active} onClick={() => {setSelected('');edit({type:'batch',productId:product.id});}}>登记现有库存</button><button className="btn" disabled={!product.active} onClick={() => {setSelected('');edit({type:'quote',productId:product.id});}}>添加报价</button></div>
      <h3 className="subheading">供应商比价 <small>同规格，按每{product.unit}比较</small></h3>{quotes.length ? <div className="quote-list">{quotes.map((q,i) => <div className="quote-row" key={q.id}><div><strong>{state.suppliers.find(s=>s.id===q.supplierId)?.name}</strong><small>{money(q.priceCents)} / {q.packSize}{product.unit} · {dateLabel(q.date)}</small></div><div><strong className={i===0?'green-text':''}>{unitPrice(q.priceCents,q.packSize)} / {product.unit}</strong>{i===0 && quotes.length>1 && <Tag tone="green">已记录报价中最低</Tag>}</div></div>)}</div> : <p className="muted">还没有报价。记录到货也会保存本次价格。</p>}
      <h3 className="subheading">库存批次 <small>点“核对”修改数量或日期</small></h3>{batchList.length ? batchList.map(b => <div className="batch-row" key={b.id}><div><strong>{b.expiryDate ? `${dateLabel(b.expiryDate)} 到期` : '到期日期待补录'}</strong><small>{dateLabel(b.receivedDate)}登记 · 上次核对 {dateLabel(b.checkedAt)}</small><span className="small muted">{b.status} {b.note && `· ${b.note}`}</span></div><strong>{b.remaining}{product.unit}</strong><button className="btn small-btn" onClick={()=>{setSelected('');edit({type:'count',batch:b});}}>核对</button></div>) : <p className="muted">还没有库存批次。请先登记现有货品或记录到货。</p>}
      <p className="notice small">这里的库存不会随微信收款自动减少，请按批次定期核对。</p></div></Modal>}
  </>;
}
