import { useState } from 'react';
import { Plus, Phone, UserRound, MessageCircle, Pencil, ArrowRight } from 'lucide-react';
import { useShop } from '../state/ShopContext';
import { Empty, Modal } from '../components/ui';
import { dateLabel, money, unitPrice } from '../lib/format';
import { latestQuotes } from '../domain/selectors';
import type { Editor } from './Editors';

export function Suppliers({edit}: {edit:(editor:Editor)=>void}) {
  const {shop,notify}=useShop(); const state=shop!.state; const [detail,setDetail]=useState(''); const s=state.suppliers.find(s=>s.id===detail);
  async function copy(text:string) { try {await navigator.clipboard.writeText(text);notify('微信号已复制。');} catch {notify('当前浏览器无法直接复制，请长按微信号复制。',true);} }
  return <><div className="page-title"><div><h1>供应商</h1><p>联系谁、进什么、多少钱，一起记清楚。</p></div><button className="btn primary" onClick={()=>edit({type:'supplier'})}><Plus size={18}/>添加供应商</button></div><div className="supplier-grid">{state.suppliers.map(s=>{const productCount=state.products.filter(p=>latestQuotes(state,p.id).some(q=>q.supplierId===s.id)).length;return <section className="panel supplier-card" key={s.id}><div className="supplier-title"><span className="supplier-avatar">{s.name.slice(0,1)}</span><div><h2>{s.name}</h2><p>{productCount}种商品有报价</p></div><button className="icon-btn" aria-label={`编辑${s.name}`} onClick={()=>edit({type:'supplier',supplier:s})}><Pencil size={18}/></button></div><div className="contact-line"><UserRound size={17}/><span>{s.contact||'未填写联系人'}</span></div><div className="contact-line"><Phone size={17}/>{s.phone?<a href={`tel:${s.phone.replace(/[^\d+ -]/g,'')}`}>{s.phone}</a>:<span className="muted">未填写电话</span>}</div><div className="contact-line"><MessageCircle size={17}/><span>{s.wechat||'未填写微信号'}</span>{s.wechat&&<button className="link-btn" onClick={()=>void copy(s.wechat)}>复制</button>}</div>{s.note&&<p className="supplier-note">{s.note}</p>}<button className="supplier-footer" onClick={()=>setDetail(s.id)}>商品报价与进货记录 <ArrowRight size={17}/></button></section>;})}</div>{!state.suppliers.length&&<section className="panel"><Empty title="把熟悉的供应商记在这里" description="留下商品、报价和联系方式，下次补货就不用翻聊天记录。"><button className="btn primary" onClick={()=>edit({type:'supplier'})}>添加供应商</button></Empty></section>}
    {s&&<Modal title={s.name} onClose={()=>setDetail('')} wide><div className="modal-body"><h3 className="subheading">最近报价</h3>{state.products.flatMap(p=>latestQuotes(state,p.id).filter(q=>q.supplierId===s.id).map(q=><div className="quote-row" key={q.id}><div><strong>{p.name} · {p.spec}</strong><small>{dateLabel(q.date)} · {money(q.priceCents)} / {q.packSize}{p.unit}</small></div><strong>{unitPrice(q.priceCents,q.packSize)}/{p.unit}</strong></div>))}<button className="btn gap-top" onClick={()=>{setDetail('');edit({type:'quote'});}}>记录一条报价</button><h3 className="subheading">这家供应商的进货记录</h3>{state.purchases.filter(p=>p.supplierId===s.id).length?state.purchases.filter(p=>p.supplierId===s.id).slice().reverse().map(p=><div className="quote-row" key={p.id}><div><strong>{p.productName}</strong><small>{dateLabel(p.date)} · {p.quantity}{p.unit}</small></div><strong>{money(p.totalCents)}</strong></div>):<p className="muted">暂无到货记录。</p>}</div></Modal>}
  </>;
}
